---
sidebar: sidebar 
permalink: concept-digital-wallet.html 
keywords: digital wallet, bluexp digital wallet, licensing, licenses, services, supported services 
summary: 'La cartera digital de BlueXP te permite gestionar y supervisar las licencias de BlueXP adquiridas en NetApp (BYOL), las suscripciones de BlueXP Marketplace y NetApp Keystone.' 
---
= Más información sobre la cartera digital de BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La cartera digital de BlueXP te permite gestionar y supervisar las licencias de BlueXP adquiridas en NetApp (BYOL), las suscripciones de BlueXP Marketplace y NetApp Keystone.



== Funciones

* Gestione las licencias basadas en capacidad y en nodos de Cloud Volumes ONTAP
* Añade y gestiona licencias para los servicios de datos de BlueXP
* Gestiona las suscripciones a PAYGO y los contratos anuales asociados con tu cuenta de BlueXP y a Astra Control
* Gestione los servicios de suscripción de Keystone para su uso con Cloud Volumes ONTAP y solicite cambios en la capacidad comprometida
* Vea la información de estado del contrato de hardware y software de los clústeres de ONTAP en las instalaciones




== Servicios compatibles

La cartera digital de BlueXP permite gestionar las licencias para lo siguiente:

* Backup y recuperación
* Clasificación
* Cloud Volumes ONTAP
* Clústeres de ONTAP en las instalaciones
* Organización en niveles

