---
sidebar: sidebar 
permalink: concept-digital-wallet.html 
keywords: digital wallet, bluexp digital wallet, licensing, licenses, services, supported services 
summary: 'La cartera digital de BlueXP te permite gestionar y supervisar las licencias de BlueXP adquiridas en NetApp (BYOL), las suscripciones de BlueXP Marketplace y NetApp Keystone.' 
---
= Más información sobre la cartera digital de BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La cartera digital de BlueXP  te permite gestionar y supervisar las licencias de BlueXP  que se han adquirido de NetApp (BYOL), las suscripciones del mercado de servicios de datos de BlueXP  (incluido NetApp Cloud Volumes ONTAP) y NetApp Keystone.



== Cómo se muestran las licencias y las suscripciones en la cartera digital

Las licencias y suscripciones se muestran automáticamente en la cartera digital cuando la cuenta de BlueXP  que se utilizó para suscribirse también es una cuenta en el sitio de soporte de NetApp. Si ha usado una cuenta de BlueXP  que no está asociada con su cuenta del sitio de soporte de NetApp (NSS), deberá añadir y actualizar licencias manualmente y no verá cambiar el uso, la capacidad ni otros detalles.


NOTE: Debe haber desplegado un conector para ver la información de suscripción en la cartera digital. También se necesita un conector para ver las licencias de nodos para Cloud Volumes ONTAP.

Mientras tanto, BlueXP consulta automáticamente al servicio de licencias de NetApp para obtener detalles sobre las licencias asociadas a su cuenta de la página de soporte de NetApp. Si no se producen errores, BlueXP añade automáticamente las licencias a la cartera digital.

Si BlueXP  no puede agregar la licencia, deberá añadirla manualmente a la cartera digital. Por ejemplo, si su cuenta de usuario de BlueXP  no está asociada con su cuenta del sitio de soporte de NetApp, tendrá que añadir dichas licencias.

Después de adquirir una licencia de su representante de ventas de NetApp, NetApp le envía un correo electrónico con el número de serie y la información adicional sobre las licencias. Necesitará ese número de serie para agregar o actualizar la licencia correspondiente en la cartera digital.

https://docs.netapp.com/us-en/bluexp-setup-admin/task-adding-nss-accounts.html["Aprenda a añadir su cuenta del sitio de soporte de NetApp a las credenciales de usuario de BlueXP "^].



== Servicios compatibles

La cartera digital de BlueXP  permite gestionar las licencias y las suscripciones para los siguientes servicios:

* https://docs.netapp.com/us-en/bluexp-backup-recovery/index.html["Backup y recuperación"^]
* https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^]
* https://docs.netapp.com/us-en/bluexp-disaster-recovery/index.html["Recuperación tras siniestros"^] (Solo BYOL)
* https://docs.netapp.com/us-en/bluexp-ransomware-protection/index.html["Protección contra ransomware"^]
* https://docs.netapp.com/us-en/bluexp-ontap-onprem/index.html["Clústeres de ONTAP en las instalaciones"^]
* https://docs.netapp.com/us-en/bluexp-tiering/index.html["Organización en niveles"^]

