---
sidebar: sidebar 
permalink: concept-digital-wallet.html 
keywords: digital wallet, bluexp digital wallet, licensing, licenses, services, supported services 
summary: 'La cartera digital de BlueXP te permite gestionar y supervisar las licencias de BlueXP adquiridas en NetApp (BYOL), las suscripciones de BlueXP Marketplace y NetApp Keystone.' 
---
= Más información sobre la cartera digital de BlueXP
:hardbreaks:
:allow-uri-read: 
:nofooter: 
:icons: font
:linkattrs: 
:imagesdir: ./media/


[role="lead"]
La cartera digital de BlueXP te permite gestionar y supervisar las licencias de BlueXP adquiridas en NetApp (BYOL), las suscripciones de BlueXP Marketplace y NetApp Keystone.



== Funciones

* Gestione las licencias basadas en capacidad y en nodos de Cloud Volumes ONTAP
* Añade y gestiona licencias para los servicios de datos de BlueXP
* Gestiona las suscripciones a PAYGO y los contratos anuales asociados con tu cuenta de BlueXP y a Astra Control
* Gestiona los servicios de suscripción de Keystone para su uso con Cloud Volumes ONTAP y clústeres de ONTAP en las instalaciones, y solicita cambios en la capacidad comprometida
* Vea la información de estado del contrato de hardware y software de los clústeres de ONTAP en las instalaciones




== Servicios compatibles

La cartera digital de BlueXP permite gestionar las licencias para los siguientes servicios:

* https://docs.netapp.com/us-en/bluexp-backup-recovery/index.html["Backup y recuperación"^]
* https://docs.netapp.com/us-en/bluexp-cloud-volumes-ontap/index.html["Cloud Volumes ONTAP"^]
* https://docs.netapp.com/us-en/bluexp-disaster-recovery/index.html["Recuperación tras siniestros"^] (Solo BYOL)
* https://docs.netapp.com/us-en/bluexp-ransomware-protection/index.html["Protección contra ransomware"^]
* https://docs.netapp.com/us-en/bluexp-ontap-onprem/index.html["Clústeres de ONTAP en las instalaciones"^]
* https://docs.netapp.com/us-en/bluexp-tiering/index.html["Organización en niveles"^]



TIP: La cartera digital de BlueXP  también te permite gestionar licencias para la clasificación de BlueXP . Sin embargo, la clasificación BlueXP  ahora está disponible como funcionalidad básica dentro de BlueXP  sin coste adicional. Ya no se necesita una licencia o suscripción. https://docs.netapp.com/us-en/bluexp-classification/concept-cloud-compliance.html["Más información sobre la clasificación de BlueXP"^]
