---
settings:
  name: BlueXP digital wallet
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: es-es,us-en,de-de,fr-fr,it-it,pt-br,ja-jp,ko-kr,zh-cn,zh-tw
sidebar:
  entries:
  - title: Documentos de la cartera digital de BlueXP
    url: "/index.html"
  - title: Notas de la versión
    entries:
    - title: Novedades
      url: "/whats-new.html"
  - title: Manos a la obra
    entries:
    - title: Más información sobre la cartera digital de BlueXP
      url: "/concept-digital-wallet.html"
  - title: Utiliza la cartera digital de BlueXP
    entries:
    - title: Utilice el panel Visión general
      url: "/task-homepage.html"
    - title: Gestionar licencias
      entries:
      - title: Gestionar licencias directas
        url: "/task-manage-data-services-licenses.html"
      - title: Gestionar licencias de Cloud Volumes ONTAP
        entries:
        - title: Licencias basadas en capacidad para Cloud Volumes ONTAP
          url: "/task-manage-capacity-licenses.html"
        - title: Licencias basadas en nodos para Cloud Volumes ONTAP
          url: "/task-manage-node-based-licenses.html"
    - title: Gestionar ofertas privadas
      entries:
      - title: Administrar una oferta privada de AWS para BlueXP
        url: "/task-manage-private-aws.html"
      - title: Administrar una oferta privada de Azure para BlueXP
        url: "/task-manage-private-azure.html"
      - title: Administrar una oferta privada de Google Cloud para NetApp BlueXP
        url: "/task-manage-private-google-cloud.html"
    - title: Gestionar suscripciones de Marketplace
      url: "/task-manage-subscriptions.html"
    - title: Gestiona las suscripciones de Keystone
      url: "/task-manage-keystone.html"
    - title: Gestione las licencias de ONTAP en las instalaciones
      url: "/task-manage-on-prem-clusters.html"
    - title: Conocimiento y apoyo
      entries:
      - title: Regístrese para recibir soporte
        url: "/task-support-registration.html"
      - title: Obtenga ayuda
        url: "/task-get-help.html"
    - title: Avisos legales
      url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
