---
settings:
  name: BlueXP digital wallet
  platform: cloud
  internal:
    pdf_enabled: true
  prod:
    pdf_enabled: true
    harmony_enabled: false
  langs: es-es,us-en,ja-jp,ko-kr,zh-cn,zh-tw,de-de,fr-fr,it-it
sidebar:
  entries:
  - title: Documentos de la cartera digital de BlueXP
    url: "/index.html"
  - title: Notas de la versión
    entries:
    - title: Novedades
      url: "/whats-new.html"
  - title: Manos a la obra
    entries:
    - title: Más información sobre la cartera digital de BlueXP
      url: "/concept-digital-wallet.html"
  - title: Utiliza la cartera digital de BlueXP
    entries:
    - title: Gestionar licencias de Cloud Volumes ONTAP
      entries:
      - title: Licencias basadas en capacidad
        url: "/task-manage-capacity-licenses.html"
      - title: Licencias basadas en nodos
        url: "/task-manage-node-based-licenses.html"
    - title: Gestiona las licencias para los servicios de datos de BlueXP
      url: "/task-manage-data-services-licenses.html"
    - title: Gestionar suscripciones y contratos de PAYGO
      url: "/task-manage-subscriptions.html"
    - title: Gestiona las suscripciones de Keystone
      url: "/task-manage-keystone.html"
    - title: Gestiona las licencias para clústeres de ONTAP en las instalaciones
      url: "/task-manage-on-prem-clusters.html"
  - title: Conocimiento y apoyo
    entries:
    - title: Regístrese para recibir soporte
      url: "/task-support-registration.html"
    - title: Obtenga ayuda
      url: "/task-get-help.html"
  - title: Avisos legales
    url: "/legal-notices.html"
product-family:
  name: BlueXP
  repo: bluexp-family
